version: '2'
services:
  app:
    volumes:
      - .:/calc:delegated
    command: python manage.py runserver 0.0.0.0:${DOCKER_EXPOSED_PORT}
    environment:
      - DEFAULT_DEBUG_EMAIL_URL=smtp://mailcatcher:25/
      - WD_CHROME_ARGS=--headless --no-sandbox --disable-setuid-sandbox
    links:
      - mailcatcher
  gulp:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/calc:delegated
    command: gulp
  rq_worker:
    volumes:
      - .:/calc:delegated
    environment:
      - DEFAULT_DEBUG_EMAIL_URL=smtp://mailcatcher:25/
    links:
      - mailcatcher
  rq_scheduler:
    volumes:
      - .:/calc:delegated
    environment:
      - DEFAULT_DEBUG_EMAIL_URL=smtp://mailcatcher:25/
    links:
      - mailcatcher
  mailcatcher:
    image: tophfr/mailcatcher:latest
    ports:
      - 1080:80
