---
defaults: &defaults
  services:
    - calc-db
    - calc-env
    - calc-redis32
  buildpack: python_buildpack
  stack: cflinuxfs2
  timeout: 180

applications:
- name: calc-prod
  <<: *defaults
  instances: 2
  memory: 1G
  disk_quota: 1024M
  routes:
    - route: calc.gsa.gov
    - route: calc-prod.app.cloud.gov
  command: bash cf.sh
  env:
    NEW_RELIC_APP_NAME: "CALC (production)"
    NEW_RELIC_CONFIG_FILE: "newrelic.ini"
    NEW_RELIC_ENV: "production"
    NEW_RELIC_LOG: "stdout"

- name: calc-rqworker
  <<: *defaults
  no-route: true
  health-check-type: none
  instances: 1
  memory: 512M
  command: python manage.py rqworker default

- name: calc-rqscheduler
  <<: *defaults
  no-route: true
  health-check-type: none
  instances: 1
  memory: 512M
  command: python manage.py rqscheduler
  env:
    IS_RQ_SCHEDULER: "yup"
